INSERT INTO article (title,content) VALUES ('제목 1','내용 1')
INSERT INTO article (title,content) VALUES ('제목 2','내용 2')
INSERT INTO article (title,content) VALUES ('제목 3','내용 3')
INSERT INTO article (title,content) VALUES ('제목 4','내용 4')
INSERT INTO article (title,content) VALUES ('제목 5','내용 5')
